app = "cuddy-pro-admin"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile.fly"

  [build.args]
    NEXT_PUBLIC_ADMIN_URL = "https://admin.cuddy.uz"
    NEXT_PUBLIC_API_URL = "https://api.cuddy.uz"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

